apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: ${INFLUXDB_DB}
    user: ${INFLUXDB_USER}
    secureJsonData:
      password: ${INFLUXDB_USER_PASSWORD}
    jsonData:
      httpMode: GET
      httpHeaderName1: ""
      timeInterval: "10s"
      version: InfluxQL
    isDefault: true
